### ISSUE TITLE
Error running automoton.py

### ISSUE THREAD

**Issue by rouson** [FEST3D/FEST-3D#5]
I built FEST-3D inside Lubuntu Linux using the steps in the README.md.  The steps completed without error.  I then cloned the FEST-3D [run] repository, attempted to run the python script, which generated the following error:  
```
$ python automaton.py 
Traceback (most recent call last):                                                                                                                                   
  File "automaton.py", line 347, in <module>                                                                                                                         
    CheckInput(ExpectedControl, ExpectedScheme, ExpectedFlow, ExpectedOutputControl, ExpectedResidualControl, Control, Scheme, Flow, OutputControl, ResidualControl)
  File "automaton.py", line 187, in CheckInput
    assert all(variable in ExpectedOutputControl['In'] for variable in OutputControl['In'])
AssertionError
```
Also, I don't understand how to set the variables mentioned in the FEST-3D run repository README.md.  For example, in the following text:

"First we need to create a directory to perform simulation and save all the input/output data.
RunDir = 'Test' Give any name to the Run directory"

I don't see any explanation of where to put the above `RunDir = 'Test'` command.  Is `RunDir` a shell environment variable or should it be set in a file and, if so, what file?

[run]: https://github.com/FEST3D/run

**Comment by rouson** [comment]
I see that another reviewer encountered the same error [here].  I strongly suggest that if two reviewers independently encountered the same problem, then the documentation needs improvement. At a minimum, the README.md file could state something like, "Edit the automoton.py file to replace the sample values before attempting to run the file."   Because I am not a python programmer, it would never have occurred to me to even open the file.  Alternatively, could you somehow set up the script so that a user who runs it without modification gets a more useful error message directing the user to edit the file before running it?  Or maybe just name the file `edit-me.py`.

Also, [Directory structure] section of the README.md file cites the scripts name as "automation.py" versus "automoton.py."

[here]: https://github.com/openjournals/joss-reviews/issues/1555#issuecomment-521937462
[Directory structure]: https://github.com/FEST3D/run#directory-structure

**Comment by jayten** [comment]
@rouson 
 
 I have made the suggested changes in the run directory. Please review them [here](https://github.com/FEST3D/run/commit/593e8983f6dca79cbbfd5f36932ec3f8f7b1cc0e). I will try to work on other issues as soon as possible.
